### PR TITLE
Sound playback and WAVE files!

### PR DESCRIPTION
**Pull request by soundofjw**
Through a LOT of work the following is possible:

AudioAsset *laser = Assets::RequestAudio("AudioTest/Laser.wav");
laser->Play();
## 

Audio decoders are now added more or less statically, and just need to be compiled to run. This is thanks to a static listing of decoderMap's which are used to map file extensions with decoders.
## 

```
    /**
     Plays an audio file. The deck it plays on will be freed automatically when the sound is complete.

     @param loops Number of times to loop
     @param volume Volume, between 0.0 and 1.0
     @param pan Panning, between -1.0(L) and 1.0(R), 0.0 for center
     @param pitch Pitch, 0.5 - 2.0

     @see Audio::PlaySound
     */
    void Play( int loops = 1, float volume = 1.0, float pan = 0.0, float pitch = 1.0 );
```

### CODE REVIEW

**Comment by zaphire** [comment]
Cooool. :) So far I can't get it working on Linux though. :( I get:

"Could not find a decoder for the file: AudioTest/Laser.wav"

etc. Not sure what's causing this yet...

**Comment by zaphire** [comment]
Hmm... I can't seem to find a place where you're calling RegisterDecoder... so I think decoderMap is empty...

**Comment by soundofjw** [comment]
It sounds like decoderMap may be empty indeed.

Decoders are registered at their construction in the super for AudioDecoder() - each decoder is declared statically in it's respective .cpp file. OggDecoder.cpp has 
static OggDecoder od;

WaveDecoder.cpp should have
static WaveDecoder wd;

It would just seem that WaveDecoder.cpp isn't being build/linked.

**Comment by soundofjw** [comment]
This should fix your problem Alec.

Mainly, the WaveDecoder folder wasn't being included, so to prevent this in the future with new decoders I moved ALL decoders to a folder Audio/Decoders. I updated CMakeLists and the vcproj accordingly, although you'll probably need to do a little merge work.

Also, OggDecoder.cpp has #ifdef MONOCLE_AUDIO_OGG or whatever it is, so you don't need to worry about that in the make/build process.

**Comment by zaphire** [comment]
Hmm, I guess my last comment didn't make it through. I tried with compiling WaveDecoder.cpp, but had the same problem.

I just pulled your latest, and I have the same problem.

Note: Content/AudioTest/Laser.wav and Coin.wav haven't been added. (files are missing)

I still get the Could not find a decoder.. problem

**Comment by soundofjw** [comment]
My best guess is that the linux build isn't declaring the oggdecoder and wavedecoder into memory. Maybe it thinks they are unused?

**Comment by zaphire** [comment]
Cool, I think this is working. :)

**Pull request merged**
