### PR TITLE
Logging into file

### PR DESCRIPTION
**Pull request by etinquis**
debug::log now redirects to a file (monocle.log) in the running directory. removed extraneous iostream includes.

### CODE REVIEW

**Comment by zaphire** [comment]
Hmm... so right now I'm using this to log stuff to a console window (in the Windows version). This ends up being pretty handy. (I can see all the messages popping up there as I'm playing the game) Maybe we could make the file and console logging options that could be toggled on/off or something?

**Comment by etinquis** [comment]
It works the same in Linux.

I'll change it around asap.  I originally intended to make it optional, I don't know why I didn't in the end.

**Comment by etinquis** [comment]
@Roflha This isn't solved as far as I know.  Is there a reason it was closed?

**Comment by rosshays** [comment]
@etinquis I've reopened it. The readon I had closed it was because the changes proposed seemed to be from an outdated branch and nothing had been done for it in a while. It's back now though.

**Pull request merged**
