### PR TITLE
Audio Engine Mapping

### PR DESCRIPTION
**Pull request by soundofjw**
I've begun mapping out the audio engine. These commits are mostly that (and some pull of the experimental tag, hmm - I'm getting the hang of this git stuff still).

Anyway, the base of it is that an Audio Channel will be connected to a Decoder Data which stores the information about the current playback of an asset. (One asset could be played twice, and would have two AudioDecoderData accordingly).  Decoders are the actual implementation of the audio decoding, such as OGG, WAV/PCM, etc, and will be able to handle data in memory and on disk.

### CODE REVIEW

**Comment by zaphire** [comment]
Hmm trying to merge this.... Where are the OpenAL headers and stuff? I guess you're supposed to install them? Would it be better to include them in the repo somehow? :o

**Comment by soundofjw** [comment]
The OpenAL headers are installed with OpenAL. (I built this all on a MAC, btw), so it was right in the Framework. Otherwise you'll need to setup the include directory for OpenAL. I'd say take the same approach to implementing how you are with OpenGL...

**Comment by soundofjw** [comment]
Erp, also make sure you grab some of the later changes.

**Comment by AlecHolowka** [comment]
Got stuff to build on Linux, had to change <OpenAL/al.h> -> <AL/al.h> etc
And some crazy CMake stuff.

Works in "tryaudio" branch... you might want to merge tryaudio and see if it breaks Mac stuff? :O

Not sure how to get Windows to work yet, but I guess it involves installing OpenAL or something.

**Comment by soundofjw** [comment]
This latest commit adds a preprocessor define to allow for including OpenAL/AL.h on MAC vs AL/AL.h elsewhere.

**Pull request merged**
