### PR TITLE
Default bit depth fix attempt

### PR DESCRIPTION
**Pull request by etinquis**
I've fixed the problem on the xlib end, but I'm currently flying blind on the windows version.

Can someone try it out and see how it goes?

### CODE REVIEW

**Comment by zaphire** [comment]
Cool beans. I'll test it out on Windows later today. :)

**Comment by zaphire** [comment]
Well so far I haven't noticed any problems on Windows... I'm passing in -1 as bits. So it might be working? :)

**Comment by etinquis** [comment]
@zaphire That's always good to hear.
I also thought of something else.  You might add a #define MONOCLE_DEFAULT_BITS -1 (or something) to the header and use that instead of passing -1 itself.

**Comment by zaphire** [comment]
Good call, I'll add something like that. I know some people are against using #defines, but I think for now it'll be okay. :)

**Comment by zaphire** [comment]
K pushed to "development" as MONOCLE_DETECT_COLOR_DEPTH in Platform.h. If you have a better idea of where to put it, lemme know. :)

**Comment by etinquis** [comment]
@zaphire I was thinking in Game.h because nothing in Platform necessarily needs to be called by a user of the engine.  The lowest barrier-to-entry application is a GameScene and a Game class, so you can get away with not looking at the Platform header at all and still have a functioning game.  In addition, if the user is calling Platform::Init themselves they should be subclassing Game, should be familiar with the situation, and should be including Game.h to subclass anyway.

**Pull request merged**
