### PR TITLE
Better Mac OS X Citizenship 3!

### PR DESCRIPTION
**Pull request by JoeOsborn**
Same description, since I just fixed a bug in the earlier request. Also note: thoroughly untested on Windows and Linux, but "ought to work".

Small changes: Cmd-Q now quits Monocle games on the Mac (this should probably be toggle-able, but it's such a nice thing for debugging) and ctrl-click simulates right-click (again, maybe worth a toggle, but such an expected feature for Mac people).

The big change: platforms can now define default content paths. The Mac version uses two build settings to decide where to look for resources:

MONOCLE_CONTENT_PATH replaces the old custom working directory settings for executables, and during release builds Xcode copies the game resources from here to the application bundle's resources folder. This path is relative to the project file, which means that Monocle now requires no tweaking to git clone and build.
(Debug: "${SRCROOT}/../../../"; Release: "")

MONOCLE_MAC_USE_CONTENT_PATH tells a development build that it should read from and write to the content path rather than the bundle's resources directory.
(Debug: "true"; Release: "false")

The long and short of it is that packaged builds will automatically look for resources in their bundle (since they won't see those environment variables) and debug builds will read from and write to resources in a preordained spot in the filesystem.

All platforms now have the concept of a "default content path" for Assets, and for the Mac it's determined as written above. For Windows and Linux, the default path is "../../Content/", which I know is problematic but seems most demo-appropriate until we get reasonable defaults for them or a similar build setup (like "./", but ideally we'd just be able to say "for the ogmo demo, for all platforms, the asset path is ./Ogmo or ./Content/Ogmo"). Demos have all been updated to append their content subpath to the current Assets content path.

### CODE REVIEW

**Comment by zaphire** [comment]
I don't think this changed anything... I had the environment variable set in by pulling the last pull request...

So maybe it's something else?

**Comment by JoeOsborn** [comment]
Was it the environment variable or the build variable before? There are both (one in build settings and one in the current scheme). It's also possible that the old scheme is still being used and needs to be zapped. I've just tried a fresh clone of your repo followed by a pull from mine, and it works great -- so I think stale Xcode settings might be to blame?

**Comment by zaphire** [comment]
Tried Release, same problem. (not finding content) I think it was just the path variable before. (MONOCLE_CONTENT_PATH)

Not sure what you mean by schemes being zapped... or what schemes even are. I know pulled the new scheme file, that's about it.

**Comment by JoeOsborn** [comment]
I'm not sure I understand what the settings are like on your end at this point. Does [this video](http://joe.lt3.us/Settings.m4v) show any differences between my setup and yours? Also, are you using Xcode 4?

**Comment by zaphire** [comment]
Hehe, I think the problem is that I don't have XCode 4. :) MY BAD.

I'll download later tonight, and I guess everything will probably work then.

**Comment by zaphire** [comment]
Hmm have XCode4 now. Things were working for a while... but the merge ended up getting borked.

So I nuked the entire Monocle-Engine directory, cloned it again, merged with your branch... now it doesn't work. :\

I don't see an environment variable in the edit scheme thing either. :S whaat.

**Comment by zaphire** [comment]
If I log out what contentPath gets set to for Tests/Ogmo...

SetContentPath: /Users/alecholowka/Library/Developer/Xcode/DerivedData/MonocleTest-gzklsdgzbthxttgejuwfxvrfkhqh/Build/Products/Debug/MonocleTest.app/Contents/Resources/Ogmo/

is that right? :|

**Comment by zaphire** [comment]
Yay it works finally. It had selected the wrong Scheme by default.

**Pull request merged**
