### PR TITLE
Output screen to bitmap

### PR DESCRIPTION
**Pull request by etinquis**
Added ScreenToBMP to Graphics.  Outputs whatever is currently in the GL out to a bitmap at the given filename/path.

### CODE REVIEW

**Comment by zaphire** [comment]
Since we're using stb_image.c to load images, maybe we want to also use http://nothings.org/stb/stb_image_write.h .

Writes to PNG, BMP, TGA. :)

**Comment by etinquis** [comment]
Done deal

**Comment by zaphire** [comment]
I think you might have to git add stb_image_write.h and commit/push it first. (not seeing it in the commit logs) Or I guess I could do it, but makes sense to include it all in this pull request. :)

**Comment by etinquis** [comment]
fixed

**Pull request merged**
